### ISSUE TITLE
Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array

### ISSUE THREAD

**Issue by fpcimmino** [vyuldashev/nova-permission#105]
Hi,
I've this error: **Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array, object given, called in /opt/bitnami/apps/lumbelumbe/htdocs/nova/src/Fields/BooleanGroup.php on line 32** when I open the roles page in nova laravel.

Can anyone help me?

**Comment by Leotrimlota** [comment]
I am having the same issue
