### ISSUE TITLE
2.4.1 BooleanGroup error when creating a role

### ISSUE THREAD

**Issue by jwktje** [vyuldashev/nova-permission#109]
Fresh install gives me this error on creating a role

```
{
    "message": "Class 'Laravel\\Nova\\Fields\\BooleanGroup' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/vendor/vyuldashev/nova-permission/src/PermissionBooleanGroup.php",
    "line": 12,
    "trace": []
}
```

**Comment by jwktje** [comment]
I figured out this was because of an outdated Nova version. 

Follow up question before you close this issue;

Is there a way to display RoleBooleanGroup in the list by default without having to click "View"?

**Comment by pzmarzly** [comment]
> Is there a way to display RoleBooleanGroup in the list by default without having to click "View"?
> 
> What I ideally would want is :
> 
>     * Have one role per user
> 
>     * Show that role directly in the index view of the Users

Try putting this in your `fields()` method:

```php
RoleBooleanGroup::make(__('Roles'), 'roles')->hideFromIndex(),
Text::make(__('Role'), function () {
    return $this->roles->map->name->join(', ');
})->onlyOnIndex(),
```
