### ISSUE TITLE
How associate Roles to Permission?

### ISSUE THREAD

**Issue by stonkeep** [vyuldashev/nova-permission#11]
Have how you construct a view to associate permissions to role?
tks

**Comment by vyuldashev** [comment]
You can attach permissions to role on Role Details page.

![screen shot 2018-08-27 at 17 18 09](https://user-images.githubusercontent.com/1809081/44664901-3ed94500-aa1d-11e8-8a7c-c608e4485da9.png)

**Comment by stonkeep** [comment]
thanks
