### ISSUE TITLE
How to get permissions attached to a role to be shown as selected on User Details/Edit User screens?

### ISSUE THREAD

**Issue by ITango** [vyuldashev/nova-permission#110]
- Laravel Version: 6.7

- Nova Version: 2.9.2

- vyuldashev/nova-permission: 2.4.1

**Question**

How can I get the permissions attached to a role to be shown as selected on the User Details and Edit User screens?

In the first screenshot below an Admin role has 3 permissions attached (view accounts, invoices, and subscriptions).

<img width="1000" alt="Screen Shot 2019-12-13 at 4 35 49 pm" src="https://user-images.githubusercontent.com/11846530/70805546-7fb8c100-1dfc-11ea-833b-3e1e0fd528ec.png">

The other two screenshots show User Details and Edit User screens for Test Account that has an Admin role attached. However, the Admin role permissions (view accounts, invoices, and subscriptions) are not shown as selected.

<img width="1000" alt="Screen Shot 2019-12-13 at 4 36 18 pm" src="https://user-images.githubusercontent.com/11846530/70805597-a24ada00-1dfc-11ea-8f97-5ba334649425.png">

<img width="1212" alt="Screen Shot 2019-12-13 at 4 36 33 pm" src="https://user-images.githubusercontent.com/11846530/70805611-aecf3280-1dfc-11ea-906c-edeae19199ae.png">

**Comment by SDCCardsDeveloper** [comment]
Same here :)

**Comment by bilfeldt** [comment]
One way to achieve this would be to make a viewOnly field that uses the `getPermissionsViaRoles()` methods from [spatie/laravel-permission](https://docs.spatie.be/laravel-permission/v3/basic-usage/role-permissions/):

``` php
// Direct permissions
$user->getDirectPermissions() // Or $user->permissions;

// Permissions inherited from the user's roles
$user->getPermissionsViaRoles();

// All permissions which apply on the user (inherited and direct)
$user->getAllPermissions();
```

**Comment by ITango** [comment]
Another way to do it is as below:

RoleBooleanGroup::make('Roles'),
PermissionBooleanGroup::make('Permissions')->resolveUsing(function ($permissions, $user) {
    $values = [];
    foreach ($user->getAllPermissions() as $item) {
        $values[$item->name] = true;
    }

    return $values;
}),

**Comment by olipayne** [comment]
This does not remove those permissions however, once the role is removed from the user
