### ISSUE TITLE
Argument 1 passed to Vyuldashev\\NovaPermission\\RoleBooleanGroup::Vyuldashev\\NovaPermission\\{closure}() must be an instance of Illuminate\\Support\\Collection, null given

### ISSUE THREAD

**Issue by aniket-magadum** [vyuldashev/nova-permission#114]
I followed the setup in the README file. I am able to use the MorphToMany fields inside of the App\Nova\User class.

But when I tried to use the RoleBooleanGroup Field I get the error message.
Laravel Nova: v2.9.2
Spatie Permissions: 3.5.0

**Comment by renanpicanco** [comment]
Same here.

**Comment by aniket-magadum** [comment]
@renanpicanco I will modify the issue later for better discussion

**Comment by renanpicanco** [comment]
@aniket-magadum I have changed laravel nova to v2.8 and nova permissions work fine

**Comment by aniket-magadum** [comment]
Alright @renanpicanco I will try it . Thankyou so much I will keep this issue open maybe someone can fix it

**Comment by aniket-magadum** [comment]
@renanpicanco I was able to fix this on the current version of Nova. I was missing the HasRoles Trait on the App\User Model

**Comment by renanpicanco** [comment]
@aniket-magadum it's worked for me too.

**Comment by szabizs** [comment]
Adding the HasRoles Trait to the App\User model also solved my issue.
