### ISSUE TITLE
How to use this package into nova resources?

### ISSUE THREAD

**Issue by starloungeswitzerland** [vyuldashev/nova-permission#120]
Hi,
I have used Spatie Permission in a lot of Laravel projects, with blade directives. 
How can use it with this package into nova resources?
Many thanks in advance..

**Comment by bilfeldt** [comment]
Laravel Nova uses Policies: https://nova.laravel.com/docs/3.0/resources/authorization.html#authorization

So implement the permission check in your policy methods.
