### ISSUE TITLE
where is the sql file?

### ISSUE THREAD

**Issue by lifeblood** [vyuldashev/nova-permission#126]
when I install the nova-permission 
click user page

![image](https://user-images.githubusercontent.com/3621748/79231715-12479a80-7e99-11ea-809e-f4b4cda857ca.png)

**Comment by svenvanhees** [comment]
Did you install the https://github.com/spatie/laravel-permission package?
Please follow this guide. https://docs.spatie.be/laravel-permission/v3/installation-laravel/

**Comment by lifeblood** [comment]
````
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at');
        });
````
