### ISSUE TITLE
Call to undefined method App\Models\User::roles() 

### ISSUE THREAD

**Issue by rangerbiru** [vyuldashev/nova-permission#151]
Hi, i just instaled this package and i got a message error `Call to undefined method App\Models\User::roles() ` and `Call to undefined method App\Models\User::permissions() `.

**Comment by martinkolarov** [comment]
Make sure to publish the migrations for the `Spatie\Permission\PermissionServiceProvider`, as well as add the `HasRoles` trait to your User model. Those steps are not documented in the installation, but are absolutely necessary to get this package working.
