### ISSUE TITLE
customizing RoleSelect

### ISSUE THREAD

**Issue by xoco70** [vyuldashev/nova-permission#156]
Hi, 

I have a role select that gives me 3 roles: SuperAdmin, Admin, Consumer

I works great when SuperAdmin is logged with

`RoleSelect::make('Role', 'roles'),`

It gives me a list with 3 roles.

But when Admin is logged, I would like to be able to use RoleSelect, but instead of having 3 results, I want to have 2 ( An admin should not be able to create a Super Admin )

I tried to define a Role Policy 

```
public function view(User $user)
    {
        return $user->roles[0]->hasPermissionTo("view role details") && $user->roles[0]->id != User::SUPER_ADMIN_ID;
    }
```

but it doesn't work.

If I use a belongsTo field, witht: 

`BelongsTo::make('Role', 'roles', \Vyuldashev\NovaPermission\Role::class),`

I get: 

`Property [guard_name] does not exist on this collection instance`

Any idea how to do it ?

**Comment by biancarosenbaum** [comment]
You are able to add the options method to RoleSelect, and then you can customize the array based on the user's role.

```
RoleSelect::make('Role', 'roles')
                ->options([
                    'volunteer' => 'volunteer',
                    'volunteer administrator' => 'volunteer administrator',
                ]),
```

**Comment by xoco70** [comment]
This is working great, closing !
