### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by dualklip** [vyuldashev/nova-permission#160]
If the project is running on PHP 7.4 appears errors related with variables not types
```sh
Type of Vyuldashev\NovaPermission\Role::$title must be string (as in class Laravel\Nova\Resource)
```
Could we create a new branch to have a version ready for PHP 7.4?  already have a Fork ready waiting to be tested
https://github.com/dualklip/nova-permission

**Comment by dualklip** [comment]
#161

**Comment by vyuldashev** [comment]
Fixed by #161

**Comment by Jamesking56** [comment]
This breaks in PHP 8 for me with this:

```
PHP Fatal error:  Type of Vyuldashev\NovaPermission\Permission::$title must not be defined (as in class Laravel\Nova\Resource) in /home/runner/work/social-mind-platform/social-mind-platform/vendor/vyuldashev/nova-permission/src/Permission.php on line 166
```

`laravel/nova` version 3.25.0 (latest version)

**Comment by dualklip** [comment]
Thank you for the report  @Jamesking56 

Now I'm trying to figure out why these lines are the right solutions in each version and how to implement a solution for all versions:

PHP 7.3
```php
public static $title = 'name';
```
PHP 7.4
```php
public static string $title = 'name';
```
PHP 8.0
```php
public static $title = 'name';
```

any idea?

**Comment by Jamesking56** [comment]
I personally think this should match the latest nova version and not include any parameter types at all.
