### ISSUE TITLE
Installation issues on v3

### ISSUE THREAD

**Issue by ale1981** [vyuldashev/nova-permission#163]
Laravel 8.41
Nova 3.25
Spatie 4.01

I have followed installation instructions but I am getting lots of errors, is this package compatible with the latest versions of Nova  and Spatie?

After registering the tool I get the following error, am wondering if I have missed a step!

Type of Vyuldashev\NovaPermission\Role::$title must not be defined (as in class Laravel\Nova\Resource) {"userId":6,"e
xception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Vyuldashev\\NovaPermission\\Role::$title must not be defined
(as in class Laravel\\Nova\\Resource) at /var/www/intranet/vendor/vyuldashev/nova-permission/src/Role.php:0)

Type of Vyuldashev\NovaPermission\Role::$search must not be defined (as in class Laravel\Nova\Resource) {"userId":6,"
exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Vyuldashev\\NovaPermission\\Role::$search must not be define
d (as in class Laravel\\Nova\\Resource) at /var/www/intranet/vendor/vyuldashev/nova-permission/src/Role.php:0)

**Comment by mustafaaloko** [comment]
I faced this on my project as well. It's a single issue that will be thrown for multiple fields. 

The cause is this commit: https://github.com/vyuldashev/nova-permission/commit/469fca9001422a08c4238b6dd04f4f29e56c61cd

@ale1981 can you please change the issue title to something like "Installation issue on v3" so it's more specific for others who come?

**Comment by halberio** [comment]
+1

**Comment by sirdharma** [comment]
Hello,

We have the same issue.

Running `laravel/nova` version `3.26.1`.

Thank you!

**Comment by RVxLab** [comment]
Also ran into this issue with Nova 3.22 on PHP 8.0. PR submitted to fix this issue, until then use [my fork](https://github.com/RVxLab/nova-permission).

Add this to your composer.json:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rvxlab/nova-permission"
        }
    }
]
```

Then reference `dev-master` as the version for `vyuldashev/nova-permission`:

```json
{
    "require": {
        ...
        "vyuldashev/nova-permission": "dev-master"
    }
}
```

Run `composerr update vyuldashev/nova-permission` and you should be good to go.

**Comment by mrimran** [comment]
> Also ran into this issue with Nova 3.22 on PHP 8.0. PR submitted to fix this issue, until then use [my fork](https://github.com/RVxLab/nova-permission).
> 
> Add this to your composer.json:
> 
> ```json
> {
>     "repositories": [
>         {
>             "type": "vcs",
>             "url": "https://github.com/rvxlab/nova-permission"
>         }
>     ]
> }
> ```
> 
> Then reference `dev-master` as the version for `vyuldashev/nova-permission`:
> 
> ```json
> {
>     "require": {
>         ...
>         "vyuldashev/nova-permission": "dev-master"
>     }
> }
> ```
> 
> Run `composer update vyuldashev/nova-permission` and you should be good to go.

Why don't you submit `pull request`?

**Comment by RVxLab** [comment]
> > Also ran into this issue with Nova 3.22 on PHP 8.0. PR submitted to fix this issue, until then use [my fork](https://github.com/RVxLab/nova-permission).
> > Add this to your composer.json:
> > ```json
> > {
> >     "repositories": [
> >         {
> >             "type": "vcs",
> >             "url": "https://github.com/rvxlab/nova-permission"
> >         }
> >     ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then reference `dev-master` as the version for `vyuldashev/nova-permission`:
> > ```json
> > {
> >     "require": {
> >         ...
> >         "vyuldashev/nova-permission": "dev-master"
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Run `composer update vyuldashev/nova-permission` and you should be good to go.
> 
> Why don't you submit `pull request`?

Read the first paragraph. ;)

**Comment by RVxLab** [comment]
[I did](https://github.com/vyuldashev/nova-permission/pull/164). Pretty sure vyuldashev only has to merge it at this point.
