### ISSUE TITLE
Error on update role and update user role

### ISSUE THREAD

**Issue by MarcosGit** [vyuldashev/nova-permission#166]
Hi, everyone i create 4 permissions with API guard name and i update all to WEB guard name and now when i try to add this permissions to role i get error 409 Conflict.

If i try to update user and add role i get error 409 Conflict with message: Other user update this resource 
since the page was loaded. Please refresh the page and try again.

When i update the page and try again i get this error again.

Please someone can help me bypass this.

![Screenshot(5)](https://user-images.githubusercontent.com/13893469/124118110-1b9a3400-da58-11eb-9457-7f49c3246bd1.png)

**Comment by RVxLab** [comment]
It sounds like something is changing your user model as you try to update it. Do you have an updating observer on that model? Check your network tab as well, maybe something is causing an update that you can see. Otherwise I recommend you install [Laravel Debug Bar](https://github.com/barryvdh/laravel-debugbar), maybe that can reveal something.

**Comment by MarcosGit** [comment]
Thank you RVxLab for your replay,
I get this error on server production and staging, on my local computer its work great.

**Comment by MarcosGit** [comment]
I dont now why i get this error but i find some thing in nova documentation, so i will move this issue to laravel nova.

Preventing Conflicts

If the model has been updated since its last retrieval, Nova will automatically respond with a 409 Conflict status code and display an error message to prevent unintentional model changes. This may occur if another user updates the model after you have opened the "Edit" screen on the resource. This feature is also known as "Traffic Cop".

Disabling Traffic Cop

If you are not concerned with preventing conflicts, you can disable the Traffic Cop feature on resource class:
`
public static $trafficCop = false;
`
