### ISSUE TITLE
Roleselect required 

### ISSUE THREAD

**Issue by kephren226** [vyuldashev/nova-permission#168]
How do I make the roleselect field required ? Or juste set a default rôle

**Comment by wijourdil** [comment]
Hello, how did you solve your problem ? :) 
I have the same issue, I have defined the field like this : 
```php
RoleSelect::make('Role', 'roles')->required(),
```

but I can submit the form without selecting a role and the User is created 🤔

**Comment by kephren226** [comment]
Hello 
This one worked for me 

RoleSelect::make('Role', 'roles')->rules('required')

**Comment by wijourdil** [comment]
Oh yeah it works for me too, thanks!
