### ISSUE TITLE
Policy vs Direct (Bug?)

### ISSUE THREAD

**Issue by Kristories** [vyuldashev/nova-permission#170]
| Package | Version |
|---|---|
| laravel/framework | v8.64.0 |
| laravel/nova | v3.29.0 |
| spatie/laravel-permission | v4.4.1 |
| vyuldashev/nova-permission | v3.0.1 

When we use `rolePolicy` and `rolePolicy`, yes it disappears from the menu. However, if we go directly to the `resources/roles` url, you can see the resource.

### `NovaServiceProvider@tools`
```
\Vyuldashev\NovaPermission\NovaPermissionTool::make()
    ->rolePolicy(RolePolicy::class)
    ->permissionPolicy(PermissionPolicy::class),
```

### `RolePolicy`
```
class RolePolicy
{
    use HandlesAuthorization;

    public function viewAny(User $user)
    {
        return false;
    }

    public function view(User $user, Role $role)
    {
        return false;
    }

    public function create(User $user)
    {
        return false;
    }

    public function update(User $user, Role $role)
    {
        return false;
    }

    public function delete(User $user, Role $role)
    {
        return false;
    }

    public function restore(User $user, Role $role)
    {
        return false;
    }

    public function forceDelete(User $user, Role $role)
    {
        return false;
    }
}
```

### `PermissionPolicy`
```
class PermissionPolicy
{
    use HandlesAuthorization;

    public function viewAny(User $user)
    {
        return false;
    }

    public function view(User $user, Permission $permission)
    {
        return false;
    }

    public function create(User $user)
    {
        return false;
    }

    public function update(User $user, Permission $permission)
    {
        return false;
    }

    public function delete(User $user, Permission $permission)
    {
        return false;
    }

    public function restore(User $user, Permission $permission)
    {
        return false;
    }

    public function forceDelete(User $user, Permission $permission)
    {
        return false;
    }
}
```
### Models : 

Both; using : 

- 1st try : `Spatie\Permission\Models\Role` and `Spatie\Permission\Models\Permission`
- 2nd try : `App\Models\Role` and `App\Models\Permission` (extending)

**Comment by nathan-io** [comment]
Hi @Kristories was this issue resolved?

**Comment by WillyReyno** [comment]
The issue is still happening on my end

**Comment by nathan-io** [comment]
@WillyReyno could you see if you still experience this when using the [kiritokatklian/nova-permission](https://github.com/kiritokatklian/nova-permission/) fork? I haven't had a chance to try it yet, as most of our Nova projects are locked to Nova v3 pending compatibility updates for several other dependencies.

**Comment by Kristories** [comment]
@nathan-io sorry late response. Issue still exists. I don't think this repo is maintained, and I'm not using it anymore.

**Comment by nathan-io** [comment]
Hi @Kristories it may have been resolved in [kiritokatklian/nova-permission/](https://github.com/kiritokatklian/nova-permission/) but I'm not sure.

**Comment by Kristories** [comment]
@nathan-io thank you. It also support Nova v4.

**Comment by nathan-io** [comment]
Hi @Kristories I'm curious, are you still seeing this issue when using kiritokatklian/nova-permission? I don't have a Nova 4 project where I can try it yet.

**Comment by Kristories** [comment]
Hi @nathan-io, i'm using https://github.com/itsmejoshua/novaspatiepermissions for now
