### ISSUE TITLE
Navigation not using viewAny Policy set to the model like Nova Resource menu

### ISSUE THREAD

**Issue by erhansogut** [vyuldashev/nova-permission#18]

**Comment by vyuldashev** [comment]
Is it package related problem?

**Comment by erhansogut** [comment]
yes i updated your navigation.blade.php

` @if (Auth::user()->can('viewAny', \Spatie\Permission\Models\Role::class) || Auth::user()->can('viewAny', \Spatie\Permission\Models\Permission::class))
<h3 class="flex items-center font-normal text-white mb-6 text-base no-underline">
    <svg class="sidebar-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <path fill="#B3C1D1"
              d="M7 10V7a5 5 0 1 1 10 0v3h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-8c0-1.1.9-2 2-2h2zm2 0h6V7a3 3 0 0 0-6 0v3zm-4 2v8h14v-8H5zm7 2a1 1 0 0 1 1 1v2a1 1 0 0 1-2 0v-2a1 1 0 0 1 1-1z"/>
    </svg>
    <span class="sidebar-label">
        Roles & Permissions
    </span>
</h3>

<ul class="list-reset mb-8">
    @can('viewAny', \Spatie\Permission\Models\Role::class)
    <li class="leading-wide mb-4 text-sm">
        <router-link :to="{
            name: 'index',
            params: {
                resourceName: 'roles'
            }
        }" class="text-white ml-8 no-underline dim">
            Roles
        </router-link>
    </li>
    @endcan
    @can('viewAny', \Spatie\Permission\Models\Permission::class)
    <li class="leading-wide mb-4 text-sm">
        <router-link :to="{
            name: 'index',
            params: {
                resourceName: 'permissions'
            }
        }" class="text-white ml-8 no-underline dim">
            Permissions
        </router-link>
    </li>
        @endcan
</ul>
@endif
`

**Comment by vyuldashev** [comment]
Can you create a PR, please?

**Comment by erhansogut** [comment]
@vyuldashev created a PR, was my first time, hope i did it correctly.

**Comment by vyuldashev** [comment]
Added comments.

**Comment by erhansogut** [comment]
Fixed #20
