### ISSUE TITLE
Translations inside the /resources/vendor/ instead of vendor/../resources

### ISSUE THREAD

**Issue by laraning** [vyuldashev/nova-permission#29]
Hi vyuldashev,

Very nice package! Congratulations for that :)

Still, I had to add a new translation folder for "pt" inside your vendor package and logically when I got your last update it got deleted.

I would suggest, if it's possible, to publish your translation files to /resources/vendor/vyuldashev/nova-permission and use a translation namespace to read them from there.

This way, each time there is a composer update, we don't lose our own translations.

Cheers and keep it up.
Bruno

**Comment by vyuldashev** [comment]
Hello,

According to Laravel documentation about [Package Development](https://laravel.com/docs/5.6/packages#translations) translations should be published to `resource_path('lang/vendor/nova-permissions-tool')`. Even Nova publishes its translations to `resources/lang/vendor/nova`.

Translations are not deleted upon composer update.
