### ISSUE TITLE
Ability to attach multiple permissions at once :)

### ISSUE THREAD

**Issue by shirshak55** [vyuldashev/nova-permission#31]
It would be better to attach multiple roles or permissions at the same time isn't it?

**Comment by phoenixg** [comment]
I would want that too.

**Comment by loveyuxiao** [comment]
use nova actions

**Comment by XGhozt** [comment]
+1

**Comment by denismarinov** [comment]
+1

**Comment by ahmedkandel** [comment]
+1
Creating a nova action could solve this but how to register the action without modifying the resource class?

**Comment by adrian-schnell** [comment]
any news here? :-)

**Comment by bolechen** [comment]
+1

 may be like the  `silvanite/novatoolpermissions` form:


![](https://raw.githubusercontent.com/Silvanite/novatoolpermissions/master/preview-addrole.png)

**Comment by ahmedkandel** [comment]
I use this package https://github.com/dillingham/nova-attach-many to attach many permission to role:

![Screenshot_1](https://user-images.githubusercontent.com/28398523/62125594-e023e780-b2cd-11e9-931e-bb679dab93db.png)

**Comment by vyuldashev** [comment]
Starting with Nova v2.6.0 you can now use `BooleanGroup` field in order to make multi select:

```php
BooleanGroup::make('Roles')->options(
    \Spatie\Permission\Models\Role::get()->pluck('name', 'id')->toArray()
),
BooleanGroup::make('Permissions')->options(
    \Spatie\Permission\Models\Permission::get()->pluck('name', 'id')->toArray()
),
```

![Screenshot 2019-11-05 at 00 09 25](https://user-images.githubusercontent.com/1809081/68158369-897b1900-ff60-11e9-9812-191116fa0c2e.png)
