### ISSUE TITLE
not able to attach anything when using postgres.

### ISSUE THREAD

**Issue by tvercruysse** [vyuldashev/nova-permission#33]
whenever i try to attach a permission to a role, a permission to a user or a role to user ( basically all use cases ) it throws an error collumn 'id' not found as below.

![image](https://user-images.githubusercontent.com/20804569/45167030-97b49480-b1f8-11e8-9943-4962c79a27b6.png)

havent had the time to research the problem yet so this could also be a nova issue.
but i guess it sure helps to be aware the problem exists.

**Comment by vyuldashev** [comment]
It may be a nova or a laravel issue. Nothing to do with this package.

**Comment by ibrunotome** [comment]
Have you solved this @tvercruysse ?

**Comment by tvercruysse** [comment]
i have worked around the issue (temporarily) by altering the permission package migration file as follows: 

1.) add increments id column.
2.) change primary composite keys to unique index by changing `$table->primary` to `$table->unique` ( i think you can just omit/delete the unique index because it has an primary id, but i left it in )

this workaround bloats the table with an extra primary column so i sure would want to revert back to the original way, but this does the trick for now :)

**Comment by ibrunotome** [comment]
I've made this too
