### ISSUE TITLE
Cache not invalidated on attaching a role or permission to user

### ISSUE THREAD

**Issue by parasume** [vyuldashev/nova-permission#4]
After attaching a role or permission to a user, the cache is not invalidated.

If you refer the `assignRole` or `givePermissionTo` methods on the `HasRoles` or `HasPermissions` traits with the spatie permission package, you can see that at the end of the method, the package invalidates the cache.

Now that Nova is attaching the role/permission, the cache is not invalidated and so any new role/permission attachment fails currently!

**Comment by drbyte** [comment]
I'm not convinced.

As long as the model has the `RefreshesPermissionCache` trait (which the default Spatie models do), then the [`saved` event should take care of clearing the cache appropriately](https://github.com/spatie/laravel-permission/blob/master/src/Traits/RefreshesPermissionCache.php#L11-L13).

I think it's working correctly. 
However, if it's not, then it would be very helpful to see a code repository where the problem exists, in order to troubleshoot it for this Nova package.

**Comment by vyuldashev** [comment]
@parasume Can you confirm that?

**Comment by parasume** [comment]
No, the cache is not invalidated on attaching a role or permission to a user. It is a bug that needs fixing

**Comment by parasume** [comment]
On second thought, I see that only the permissions are cached in the package and not the relationships. Let me check this in more detail and come back on this

**Comment by drbyte** [comment]
Interesting.

I set up a small test project and all the roles/permissions take effect immediately in the app, even while the user is still logged in, after changing/adding/deleting in Nova using this Nova package.

Hence why I'm interested in knowing what's different about yours.

**Comment by parasume** [comment]
@drbyte you are correct. Doing this with a fresh package works, the original issue is unrelated to the package. I am confused [why the spatie laravel/permission package refreshes the cache on attaching/detaching](https://github.com/spatie/laravel-permission/blob/606373716fedf1ed6868dcd278285278ad5297e1/src/Traits/HasPermissions.php#L278) though. Perhaps, this was added in case they wanted to cache the permission relationships in the future.

Nevertheless, we can close this issue

**Comment by mrmonat** [comment]
I have a similar cache problem:

Attaching Roles to Users -> the cache does get renewed
Attaching Permissions to Roles (via BelongsToMany Nova Field) -> the cache doesn't get not renewed

I think it's a problem, that Laravel does not fire events for attaching / detaching / syncing relations to models...

**Comment by mrmonat** [comment]
I can think of two ways of "fixing" this:

1. Use Relationship Events (https://github.com/chelout/laravel-relationship-events)

2. Use a custom Nova Field on Permission / Role Nova Resource instead of ```BelongsToMany``` and use the methods provided from the spatie package to attach / detach roles

**Comment by vyuldashev** [comment]
@mrmonat I was thinking about making custom fields. I have some thoughts and will work on them soon.

**Comment by vyuldashev** [comment]
Also, I am not experiencing issues with current implementation. Whenever I attach permission. Cache is invalidated.

**Comment by mrmonat** [comment]
Even when you attach a new Permisson to a Role? In my case the roles are cached with their corresponding permissons, and doesn't get renewed

**Comment by jianminLee** [comment]
You may want to override the attach/detach method in BelongsToMany, using the laravel-permission method, otherwise you can only do event monitoring through the observer. There is another question, does the "select tag" in Nova not support multiple selection?

**Comment by jasonlav** [comment]
Able to confirm the bug.

**Comment by jasonlav** [comment]
Any progress on this issue?

**Comment by parasume** [comment]
I was working on this issue to submit a PR but it had a lot of breaking changes and it actually ended up being a re-write of this package.

So, I've created a new package: https://github.com/insenseanalytics/laravel-nova-permission

Key differences are as follows:
1. Solves this issue and #45 
2. Also added the ability to use permissions based authorization for Nova resources (instead of policy based) if you'd like to do that for certain resources

Both forgetting the cache on attaching permissions and permission based authorization were critical for my application since we link permissions with roles (rather than directly). Feel free to use it if you're in a similar boat. Cheers!

**Comment by vyuldashev** [comment]
Just tagged v1.4.4, the bug should disappear now.
