### ISSUE TITLE
Use the new nova $group

### ISSUE THREAD

**Issue by julianpoma** [vyuldashev/nova-permission#40]
Just a cosmetic improvement, make use of the new nova groups to group the Permission and Roles resources, instead of the current sidebar label

`public static $group = 'Users';`

**Comment by vyuldashev** [comment]
I wish community to vote for using `$group` or using separate navigation for roles and permissions.

**Comment by richvida** [comment]
+1

**Comment by wimurk** [comment]
+1

**Comment by bolechen** [comment]
+1

**Comment by vyuldashev** [comment]
If someone will make a PR with this feature I will definitely merge it.

**Comment by vyuldashev** [comment]
Just tagged v2.2.0 with this functionality.

**Comment by babul** [comment]
Just what I was looking for. Could I get an example of how to set the group that is used for Nova navigation? Thanks!
