### ISSUE TITLE
Undefined method when going to an individual user.

### ISSUE THREAD

**Issue by Niels-P** [vyuldashev/nova-permission#48]
Hi everyone,

I'm getting an undefined method error when going to an individual user. 

I've followed the spatie permissions installation, included the line in my Nova Provider. I can create and edit roles & permissions, but as soon as I view the details of a user I get these errors down below. Did anyone experience these errors as well? Or did I just miss a step?

![schermafbeelding 2018-10-23 om 17 53 52](https://user-images.githubusercontent.com/9845073/47373711-a85b9400-d6ec-11e8-9107-80e648998725.png)

Happy to hear suggestions!

**Comment by perforsberg77** [comment]
Me too, any solution?

**Comment by doobas** [comment]
add HasRoles trait into User model

```
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;

**Comment by perforsberg77** [comment]
Works for me, thanks!

**Comment by AfikDeri** [comment]
@doobas this one should be added to the docs

**Comment by vyuldashev** [comment]
It is documented in spatie's package [readme](https://github.com/spatie/laravel-permission#usage)
