### ISSUE TITLE
User relations not work

### ISSUE THREAD

**Issue by tuxinside** [vyuldashev/nova-permission#56]
After follow your installation guide, if i try to see user, i obtain following error:

"message": "Too few arguments to function Laravel\\Nova\\Resource::__construct(), 0 passed in E:\\xampp72\\htdocs\\logvrp\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasRelationships.php on line 670 and exactly 1 expected".

This is my code inside App/Nova/User.php:

public function fields(Request $request)
    {
        return [

            ....
            MorphToMany::make('Roles', 'roles', \Vyuldashev\NovaPermission\Role::class),
            MorphToMany::make('Permissions', 'permissions', \Vyuldashev\NovaPermission\Permission::class),
            ....
        ];
    }

How can solve?

**Comment by vyuldashev** [comment]
Go through Spatie's installation guide and try again.
