### ISSUE TITLE
dose this package support Atomic Panel ?

### ISSUE THREAD

**Issue by mustafakhaleddev** [vyuldashev/nova-permission#63]
Hello , some developers asked me if this package can work in my package (atomic panel ) here
https://github.com/mustafakhaleddev/laravel-atomic
its possible to make new package with the same features for it ?

**Comment by vyuldashev** [comment]
Hello, this package is designed for Laravel Nova. And it's just a wrapper around spatie/laravel-permission library. You can use it for making a new package for other admin panels.
