### ISSUE TITLE
How do you attach roles / permissions to a Resource?

### ISSUE THREAD

**Issue by tudorradubarbu** [vyuldashev/nova-permission#66]
I cannot find anything in the documentation. How can I attach roles / permissions to work with a Resource (fields ...) ?  Do you have to make use of policies?

**Comment by Ange7** [comment]
i think @tudorradubarbu want to know is : 

With other resources (for example « news ») how can i attach roles ? ( if current user don't have « news » role, so not allowed to acces news resource.)

and i have the same question... how we can do this ? 

thanks

**Comment by bcorcoran** [comment]
@Ange7 this does not do that. This is purely for managing the roles and permissions themselves, not deciding when and where to enforce them. That is up to you via methods like ->can or ->hasRole, etc.

**Comment by abr4xas** [comment]
@tudorradubarbu @Ange7 you need to use policies

**Comment by anditsung** [comment]
> @tudorradubarbu @Ange7 you need to use policies

i have add the policies
and adding this to the policy
```
public function viewAny(User $user)
    {
        if($user->can('preparations')) return true;
    }
```
the permissions name is preparations but still return false

**Comment by abr4xas** [comment]
@anditsung you need to check if the user has that permission

**Comment by anditsung** [comment]
> @anditsung you need to check if the user has that permission

 i have try using permissionTo
still return false
