### ISSUE TITLE
How to modify Role model in vendor folder

### ISSUE THREAD

**Issue by 4unkur** [vyuldashev/nova-permission#68]
I need to add the following logic to `Role` resource. Is it possible somehow?

Currently I have added this method to Role resource under `vender` folder
```php
    public static function relatableQuery(NovaRequest $request, $query)
    {
        return $query->where('name', 'NOT LIKE', 'superadmin');
    }
```

**Comment by vyuldashev** [comment]
Role and Permission models can be changed through laravel-permission library configuration.
