### ISSUE TITLE
Bug or server config issue? /nova-spatie-laravel-permission-tool 500 (Internal Server Error)

### ISSUE THREAD

**Issue by fishmad** [vyuldashev/nova-permission#7]
```
users:17 GET http://localhost/nova-api/styles/nova-spatie-laravel-permission-tool 500 (Internal Server Error)
users:169 GET http://localhost/nova-api/scripts/nova-spatie-laravel-permission-tool 500 (Internal Server Error)
```

![image](https://user-images.githubusercontent.com/12012101/44565660-a2107080-a7ac-11e8-8430-0d848c1af2e6.png)

**Comment by vyuldashev** [comment]
This should be fixed now. Also, notice that this package was renamed to https://packagist.org/packages/vyuldashev/nova-permission. Please reinstall.

**Comment by richardkeep** [comment]
Am creating a card and I am facing this problem. What causes this?
