### ISSUE TITLE
Overriding package language

### ISSUE THREAD

**Issue by preliot** [vyuldashev/nova-permission#72]
Could you update the documentation to make overriding language clear for future users? I mean something like this:

**Override language**

Put your translations in /resources/lang/vendor/nova-permission-tool, to get you custom translations to work.

(Language files in /resources/lang/vendor/nova-permission will not work)

**Comment by sheronov** [comment]
> (Language files in /resources/lang/vendor/nova-permission will not work)

Use this path resources/lang/vendor/nova-permission-tool
