### ISSUE TITLE
canSeeWhen() without wished effect

### ISSUE THREAD

**Issue by adrian-schnell** [vyuldashev/nova-permission#74]
I added the NovaPermissionTool inside the NovaServiceProvider with:
`NovaPermissionTool::make()->canSeeWhen('userAdmin')`
only my own defined super admin can see the links now - but not the *userAdmin*.
without `canSeeWhen()` it's visible for all other backend users.

**Comment by nezaboravi** [comment]
@adrian-schnell is this a question? Where have you added NovaPermissionTool::make()->canSeeWhen('userAdmi')?

**Comment by adrian-schnell** [comment]
I added the `NovaPermissionTool::make()->canSeeWhen('userAdmin')` inside the `tools()` method of the `NovaServiceProvider`.
