### ISSUE TITLE
ForgetCachedPermissions crashes on attach edition

### ISSUE THREAD

**Issue by Kirich11** [vyuldashev/nova-permission#75]
When I'm tryin to edit a related model from BelongsToMany component. Not attach/detach but edit

#69 didn't explain the error oigin

Here's the exception:
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "~/vendor/vyuldashev/nova-permission/src/ForgetCachedPermissions.php"
line: 28
message: "Class name must be a valid object or a string"

the line is:
$permissionKey = Nova::resourceForModel(app(PermissionRegistrar::class)->getPermissionClass())::uriKey();

Seems like cannot load the correct resource

**Comment by dddeeemmmooonnn** [comment]
Same error, when not super admin

**Comment by Kirich11** [comment]
Exactly!

I have set a policy with before() method where i check for admin. And when the user is an admin everything is ok and works as expected.
But with other roles and permissions on attach/detach and pivot edit I just get an error.
@vyuldashev please, could you look into it? Or atleast mention that it's a bug or tell us where we're wrong

**Comment by Kirich11** [comment]
I think I now what causes this issue.

I've registered PermissionTool to be seen only by admins. This breaks ForgetCachePermissions

**Comment by Kirich11** [comment]
@dddeeemmmooonnn If you're still wondering what to do, here's the solution:
If you want customizable components with actions, lense and etc:

-  create customRole and customPermission Nova resources which extend Vyuldashev\NovaPermission\Role and Vyuldashev\NovaPermission\Permission
- Remove everything expect cards, filters, lenses and actions methods

For custom visibilaty:
- Create policies for roles and permissions
- Add before method which checks for admin, add other methods which return false to hide the Roles&Permissions component from others
- Register policies in the auth provider for \Spatie\Permission\Models\Permission and \Spatie\Permission\Models\Role
- Remove canSee call on registering tool
