### ISSUE TITLE
Users can give themselves any role?

### ISSUE THREAD

**Issue by shanerbaner82** [vyuldashev/nova-permission#76]
My Nova package is open to admin and users and I am restricting access to resources via this package. However, I cannot restrict access to the page where I grant roles and permissions to users, which gives them access to this tool and thus, access to anything.

How can I restrict access to this tool to certain roles/permissions?

**Comment by nezaboravi** [comment]
YEs i would lov eto know same thing

**Comment by nezaboravi** [comment]
Ok here is how i did it:
i have created isSuperAdmin in my User model.
Two ways you can tackle this:
1) make user_type field in users table and check if user is of type you want to be able to see Roles menu.
2) seed a role for your superadmin user and check it in isSuperAdmin


```
public function isSuperAdmin()
{
    // case 1
    return auth()->user()->user_type === 'superadmin';
    // case 2
    return in_array('superadmin', auth()->user()->getRoleNames()->toArray())
}
```

**Comment by dgtal** [comment]
Nice approach @nezaboravi.

Assuming that the role name is "Admin", I did this:

```
    public function tools()
    {
        return [
            \Vyuldashev\NovaPermission\NovaPermissionTool::make()
                ->canSee(function() {
                    return auth()->user()->hasRole('Admin');
                })
        ];
    }
```
