### ISSUE TITLE
User edit page, permissions and roles not visible

### ISSUE THREAD

**Issue by wimurk** [vyuldashev/nova-permission#78]
The title says it all. When i edit a user there are extra fields.
![image](https://user-images.githubusercontent.com/14072334/56638934-ae1c3d00-666f-11e9-8aba-34e284239631.png)

![image](https://user-images.githubusercontent.com/14072334/56638944-b4aab480-666f-11e9-9bd2-6cb24cdfeff3.png)

My code is like the docs. Added it to the tools array in the `serviceProivder`. Added `MorphToMany` fields to the users fields. Added middleware in config file and still no luck.

Am i missing something here?

**Comment by dgtal** [comment]
Hi @wimurk !

You should be able to add roles and permissions in the detail view.

**Comment by wimurk** [comment]
My bad. Was looking at the wrong page.

I have a feuture fequest.
Is it possible to assign multiple roles and permissions at once?
