### ISSUE TITLE
Role not found

### ISSUE THREAD

**Issue by ServerJunge** [vyuldashev/nova-permission#8]
Hi,

I followed the instruction and everything works. But when I browse to my user Resource (http://nova.test/nova/resources/users)

I get the following error.

\Vyuldashev\NovaSpatieLaravelTool\Role not found

Any idea?

**Comment by vyuldashev** [comment]
This package was renamed to https://packagist.org/packages/vyuldashev/nova-permission. Please reinstall.

**Comment by ServerJunge** [comment]
Reinstalled and get the following error on my user details. 
![image 1](https://user-images.githubusercontent.com/6726798/44587089-3af5ba80-a7b2-11e8-8aa4-ecc8dabc50f8.png)

**Comment by vyuldashev** [comment]
Looks like you did not setup `spatie/laravel-permission` completely. You need to add `HasRoles` trait to your `User` model. More information here: https://github.com/spatie/laravel-permission#usage

**Comment by ServerJunge** [comment]
You are so right... I just forgot it. Thanks!!!
