### ISSUE TITLE
Hide admin users in users list

### ISSUE THREAD

**Issue by acubino** [vyuldashev/nova-permission#80]
I want to hide / delist the 'admin' role users in the user view of nova. But not hide the user list completelly using the viewAny() method.

I know that i can manage the update and creation upon the policies but it only allow me show or hide all users.

I just overload the indexQuery method, but im dont know how to modify it. I know that i can add a $query->where() but nothing more.

    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query;
    }

Any help will be appreciated.

**Comment by phuclh** [comment]
Try:
```
public static function indexQuery(NovaRequest $request, $query)
{
    return $query->where('id', '!=', 1);
}
```
