### ISSUE TITLE
Hide Roles & Permisions in sidebar

### ISSUE THREAD

**Issue by eduardovisualpublinet** [vyuldashev/nova-permission#81]
How can I hide roles and permissions in the sidebar for other roles?

**Comment by jorgenb** [comment]
There seems to be a solution here https://github.com/vyuldashev/nova-permission/issues/35 but it would be nice if one could use policies, for example:

`AuthServiceProvider.php`
```php
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        \Vyuldashev\NovaPermission\Role::class => RolePolicy::class,
        \Vyuldashev\NovaPermission\Permission::class => PermissionPolicy::class,
    ];
```

**Comment by eduardovisualpublinet** [comment]
Thanks!

I tried to do a policy, and it didn't work.

**Comment by iBet7o** [comment]
I did the following

```
...
\Spatie\Permission\Models\Role::class => \App\Policies\RolePolicy::class,
\Spatie\Permission\Models\Permission::class => \App\Policies\PermissionPolicy::class,
...
```

¡it works!

**Comment by gavinhewitt** [comment]
> I did the following
> 
> ```
> ...
> \Spatie\Permission\Models\Role::class => \App\Policies\RolePolicy::class,
> \Spatie\Permission\Models\Permission::class => \App\Policies\PermissionPolicy::class,
> ...
> ```
> 
> ¡it works!

Does not work for me. The earlier proposed solution #35 does the trick.
