### ISSUE TITLE
It does not show the form fields

### ISSUE THREAD

**Issue by iBet7o** [vyuldashev/nova-permission#84]
I installed the package as it says in the documentation but I can not see the fields when creating a role. :(

![schreenshot](https://user-images.githubusercontent.com/590235/60550072-614a8780-9cec-11e9-8f35-4c8f07d4291e.png)

**Comment by iBet7o** [comment]
this topic is related to the version 2.0.8 of nova

**Comment by brentkozjak** [comment]
Is there anything we can do to get this working?
