### ISSUE TITLE
Select is empty when trying to attach permissions

### ISSUE THREAD

**Issue by S0ulf7y** [vyuldashev/nova-permission#88]
Hi and thanks for the package!

When I open a role in the admin panel and click on "Attach Permission" the select box on the next page is empty. Only when you start typing it suggests some of the available permissions. 

![Anmerkung 2019-08-01 090519](https://user-images.githubusercontent.com/27865472/62272524-86413000-b43b-11e9-8764-9d0c8d43fcfa.png)

I think it would be better to see all available permissions when you open the page.

Best regards
Mario

**Comment by forexgg** [comment]
same thing when open a role in the admin panel and click on "Attach User", the select box is empty.

**Comment by anditsung** [comment]
its because the dev make it searchable
maybe add a feature to make it searchable or not
