### ISSUE TITLE
Consider renaming the tool

### ISSUE THREAD

**Issue by freekmurze** [vyuldashev/nova-permission#9]
Hi,

thank you for creating this tool and using our permissions package to power it.

Something I don't like though is the use of our company name in the name of the tool. Some people might think that Spatie made this tool which is not the case. 

Could you rename it to `nova-permission` or something similar? I'd be more than happy to add a link to this tool in the readme of `spatie/laravel-permission`.

Thanks!

**Comment by vyuldashev** [comment]
Hello. No problems. I will rename it today.

**Comment by vyuldashev** [comment]
Package renamed to https://packagist.org/packages/vyuldashev/nova-permission
