### ISSUE TITLE
Support Laravel 6 / Spatie Permissions 3

### ISSUE THREAD

**Issue by RicLeP** [vyuldashev/nova-permission#92]

**Comment by vincenzoraco** [comment]
Done - https://github.com/vyuldashev/nova-permission/pull/93 - waiting for someone to approve the update.

**Comment by vyuldashev** [comment]
Tagged v2.0.0. Thanks @vincenzoraco for contribution.

**Comment by Benjacho** [comment]
Hey i have some issue on         $roleResource = Nova::resourceForModel(Role::getModel());
this returns null. Spatie 3.0, 2.1 of this package.
