### ISSUE TITLE
Laravel 6 issue

### ISSUE THREAD

**Issue by eimantaaas** [vyuldashev/nova-permission#95]
After updating to Laravel 6, I get this error:

`Symfony\Component\Debug\Exception\FatalErrorException
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Method Illuminate\Translation\Translator::getFromJson does not exist. (View: /vendor/vyuldashev/nova-permission/resources/views/navigation.blade.php)`

Laravel version: 6.0.1
Nova version: 2.2.0
Nova permission: 2.1.0
Spatie permission: 3.0

**Comment by SadeghPM** [comment]
same issue with nova 2.3.

**Comment by sten** [comment]
@eimantaaas and @SadeghPM I was able to fix it by clearing the view cache:

```php artisan view:clear```

I could only find references to `getFromJson` in view cache files.

**Comment by chorton** [comment]
I am having the same issue

**Comment by chorton** [comment]
> @eimantaaas and @SadeghPM I was able to fix it by clearing the view cache:
> 
> `php artisan view:clear`
> 
> I could only find references to `getFromJson` in view cache files.

This did nothing to help get rid of the error noted above.

**Comment by vyuldashev** [comment]
I just made a fresh install with Laravel 6 and everything works fine for me.
